# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jaronb/Projects/LC-3_VirtualMachine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jaronb/Projects/LC-3_VirtualMachine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaronb/Projects/LC-3_VirtualMachine/CMakeFiles /Users/jaronb/Projects/LC-3_VirtualMachine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jaronb/Projects/LC-3_VirtualMachine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lc3

# Build rule for target.
lc3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lc3
.PHONY : lc3

# fast build rule for target.
lc3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/build
.PHONY : lc3/fast

src/Buffer.o: src/Buffer.cpp.o

.PHONY : src/Buffer.o

# target to build an object file
src/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/Buffer.cpp.o
.PHONY : src/Buffer.cpp.o

src/Buffer.i: src/Buffer.cpp.i

.PHONY : src/Buffer.i

# target to preprocess a source file
src/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/Buffer.cpp.i
.PHONY : src/Buffer.cpp.i

src/Buffer.s: src/Buffer.cpp.s

.PHONY : src/Buffer.s

# target to generate assembly for a file
src/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/Buffer.cpp.s
.PHONY : src/Buffer.cpp.s

src/UnixBuffer.o: src/UnixBuffer.cpp.o

.PHONY : src/UnixBuffer.o

# target to build an object file
src/UnixBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/UnixBuffer.cpp.o
.PHONY : src/UnixBuffer.cpp.o

src/UnixBuffer.i: src/UnixBuffer.cpp.i

.PHONY : src/UnixBuffer.i

# target to preprocess a source file
src/UnixBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/UnixBuffer.cpp.i
.PHONY : src/UnixBuffer.cpp.i

src/UnixBuffer.s: src/UnixBuffer.cpp.s

.PHONY : src/UnixBuffer.s

# target to generate assembly for a file
src/UnixBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/UnixBuffer.cpp.s
.PHONY : src/UnixBuffer.cpp.s

src/VirtualMachine.o: src/VirtualMachine.cpp.o

.PHONY : src/VirtualMachine.o

# target to build an object file
src/VirtualMachine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/VirtualMachine.cpp.o
.PHONY : src/VirtualMachine.cpp.o

src/VirtualMachine.i: src/VirtualMachine.cpp.i

.PHONY : src/VirtualMachine.i

# target to preprocess a source file
src/VirtualMachine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/VirtualMachine.cpp.i
.PHONY : src/VirtualMachine.cpp.i

src/VirtualMachine.s: src/VirtualMachine.cpp.s

.PHONY : src/VirtualMachine.s

# target to generate assembly for a file
src/VirtualMachine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/VirtualMachine.cpp.s
.PHONY : src/VirtualMachine.cpp.s

src/WinBuffer.o: src/WinBuffer.cpp.o

.PHONY : src/WinBuffer.o

# target to build an object file
src/WinBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/WinBuffer.cpp.o
.PHONY : src/WinBuffer.cpp.o

src/WinBuffer.i: src/WinBuffer.cpp.i

.PHONY : src/WinBuffer.i

# target to preprocess a source file
src/WinBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/WinBuffer.cpp.i
.PHONY : src/WinBuffer.cpp.i

src/WinBuffer.s: src/WinBuffer.cpp.s

.PHONY : src/WinBuffer.s

# target to generate assembly for a file
src/WinBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/WinBuffer.cpp.s
.PHONY : src/WinBuffer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lc3.dir/build.make CMakeFiles/lc3.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lc3"
	@echo "... src/Buffer.o"
	@echo "... src/Buffer.i"
	@echo "... src/Buffer.s"
	@echo "... src/UnixBuffer.o"
	@echo "... src/UnixBuffer.i"
	@echo "... src/UnixBuffer.s"
	@echo "... src/VirtualMachine.o"
	@echo "... src/VirtualMachine.i"
	@echo "... src/VirtualMachine.s"
	@echo "... src/WinBuffer.o"
	@echo "... src/WinBuffer.i"
	@echo "... src/WinBuffer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

